name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@1.0.0
      - name: install sdl2
        run: |
          sudo apt-get install libsdl2-dev libsdl2-image-dev
      - name: create build directory
        run: mkdir build 
      - name: cmake directory
        working-directory: ./build
        run: cmake ..
      - name: build it
        working-directory: ./build
        run: make 
